# Generated by Django 2.2.6 on 2019-10-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='body',
        ),
    ]
