# Generated by Django 2.2.6 on 2019-10-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_essay_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='head',
            field=models.TextField(default='TLQKF'),
        ),
    ]
