# Generated by Django 2.2.6 on 2019-10-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_essay_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='head',
            new_name='body',
        ),
    ]
