# Generated by Django 2.2.6 on 2019-10-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20191031_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='authour',
            new_name='author',
        ),
    ]
